### ISSUE TITLE
Make polyagamma conda-installable

### ISSUE THREAD

**Issue by macks22** [zoj613/polyagamma#97]
I realize you've chosen `poetry` as your primary package manager, but I'd propose it would also be beneficial to have `polyagamma` available on a common conda mirror like `conda-forge`. I believe the necessary [`conda-build` files](https://conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html) are relatively straightforward, and I'd be happy to take a stab at contributing this if it's something you'd be willing to incorporate!

My particular use case is this: I have a package in which I'd like to use `polyagamma`. Currently, I can instruct my users to conda install and I can be comfortable that any hardware-optimized routines they have available (e.g. BLAS, MKL, LAPACK) will be linked correctly. However, if they have to start mixing package managers because some dependencies are not on conda, this makes it more likely some users will not end up with an ideal install.

**Comment by zoj613** [comment]
Hi @macks22 , thanks for bringing this to my attention. Having the package available on conda-force would be great. I'm happy for you to have a go at it. Does the use of `poetry` make it hard to have the package available on conda?

The package does distribute wheels for easy installation via pip (see: [files](https://pypi.org/project/polyagamma/1.3.2b2/#files), so a command like `pip install polyagamma` should work fine in a conda environment without worrying about poetry. The source distribution doesn't rely on poetry either so I think at this moment, the lack of availability of `conda-forge` should not make it hard to install for your users.

**Comment by zoj613** [comment]
Recipe has been added at https://github.com/conda-forge/staged-recipes/pull/15912

**Comment by zoj613** [comment]
@macks22 the package is now available on conda via `conda install polyagamma`

**Comment by macks22** [comment]
Thanks @zoj613! I was hoping to get to it this week, but you beat me to it! 😁

Just confirmed that I was able to `conda install polyagamma`.
